### ISSUE TITLE
Jinja2 템플릿

### ISSUE THREAD

**Issue by Unperknown** [Las-Wonho/FirstWebDevelop#12]
Flask 안의 패키지 중 Jinja2와 Flask-Bootstrap 템플릿 엔진을 사용하여 Front-end HTML 문서에 사용하는 부분이 있는데 이것을 사용하는 것이 좋을지 토의를 해보아야 할 것 같습니다.

**Comment by Unperknown** [comment]
예를 들어, HTML 구성의 뼈대가 될 수 있는 베이스 템플릿을 구성하면 Jinja2가 그 베이스 템플릿의 각 블럭들을 나누어 객체지향 언어에서 상속을 하듯이 extends를 하여 보다 더 계층화된 Front-end 작업을 할 수 있게 될 것이라고 예상합니다. 만약 Jinja2 템플릿 엔진을 사용하는데 전체가 동의하면 Client 폴더에 있는 작업물들을 다시 Jinja2로 재작성하여 Pull request를 할 예정입니다.

**Comment by Las-Wonho** [comment]
Jinja2를 쓰는 것이 나아보입니다. 어떤 템플릿을 써도 그렇게 크게 영향이 가진 않기때문에 Jinja가 더 나아보입니다.

**Comment by Mixergi** [comment]
동의합니다.

**Comment by DawonChoi** [comment]
Jinja2를 사용하는 것에 동의합니다.
