### ISSUE TITLE
로그인 구현

### ISSUE THREAD

**Issue by Unperknown** [Las-Wonho/FirstWebDevelop#14]
기본적인 템플릿 구현 및 첫 서버 구동을 마쳤으니 그 다음으로 다른 구현을 해보려고 합니다. 캐싱(Caching)은 아직 정보가 없어서 그나마 난이도가 쉬운 것부터 차근차근 하려고 합니다.
  이번에 해보려고 하는 것은 로그인 구현입니다. Flask의 Message Flashing 부분을 이용하여 Front-end 제작자가 로그인 페이지를 먼저 작성하고 나서 거기에 Jinja2 템플릿을 덮어씌워 로그인을 하면 로그인을 하였다는 메시지를 뜨게 하도록 하려고 합니다.
  이에 대해서 만약 문제점이 있거나 설계 자체에 잘못된 점이 있으면 의견을 남겨주시고 전체가 동의하면 그때부터 시작하도록 하겠습니다.

**Comment by Las-Wonho** [comment]
캐시와 같은 경우에는 [이 문서](https://pythonhosted.org/Flask-Cache/)를 부면 도움이 될 것 같습니다. 이 부분은 제가 하도록 하겠습니다.
클라이언트가 먼저 완성되야 로그인 기능을 구현이 가능 할 것 같습니다. 이번 주말에 간단하게 from을 만들겠습니다. 설계자체는 잘못된 점이 없지만, 로그인이 실패하였는지, 성공하였는지 보여주는 것은 클라이언트쪽에서 진행하는게 낫다고 생각합니다. 로그인할때마다 창이 바뀌는 것은 너무 귀찮습니다.
메인 화면 -> 로그인 화면 -> 메인 화면정도로 생각하고 있습니다. 실패창을 따로 로딩해주는 것보다는 클라이언트에서 해도 되는 부분이라고 생각합니다.

**Comment by DawonChoi** [comment]
동의합니다.

**Comment by Mixergi** [comment]
동의합니다.
