### ISSUE TITLE
새로운 팀원

### ISSUE THREAD

**Issue by Unperknown** [Las-Wonho/FirstWebDevelop#16]
어제 회의(?) 결과 정민아와 전은선이 디자인 쪽으로 팀원 영입이 되었습니다. 그런데 전은선은 일정이 있어서 나중에 하고 정민아부터 초대를 해야 합니다. [여기](https://github.com/octavesop)가 정민아 계정이니 원호 선배께서 초대해주시기 바랍니다.

**Comment by Unperknown** [comment]
그리고 README.md에도 Contributor 목록에 팀원을 추가해야 합니다. 원호 선배가 직접 수정하는 것이 빠를 것 같습니다.

**Comment by Las-Wonho** [comment]
작업하겠습니다.

**Comment by Las-Wonho** [comment]
팀원을 추가하였고, README.md에도 추가하였습니다. 작업하는김에 몇가지 수정사항에 관하여도 업데이트를 해주었습니다.

**Comment by Unperknown** [comment]
전은선 [계정](https://github.com/1463)도 저번과 같이 수정해주세요

**Comment by Unperknown** [comment]
네, 그러나 어려운 작업은 되도록 안했으면 좋겠다고 하였습니다. 그래서 전은선도 같이 디자인이나 클라이언트 쪽 작업을 할 수 있도록 하였으면 좋겠습니다.

**Comment by Las-Wonho** [comment]
알겠습니다. 오늘 클라이언트 회의할 때 이야기 하겠습니다.
