### ISSUE TITLE
프로젝트 정하기

### ISSUE THREAD

**Issue by Las-Wonho** [Las-Wonho/FirstWebDevelop#2]
어떠한 내용을 구현할 지 논의합니다.

**Comment by Unperknown** [comment]
어젯밤에 어떤 도구를 사용하여 웹 기반 서비스를 구축할 것인지, 그리고 웹 페이지에 어떤 내용을 담을지 대략적으로 구상하였습니다.

Front-end 부분을 중심으로 Back-end 부분은 현재 배경 지식의 한계에 따라 난이도가 쉬운 Python 기반의 Flask 프레임워크를 사용하기로 결정하였고 나중에 Back-end 개발 연습을 위해서 Java JSP나 Node.js로 재작성을 하기로 결정하였습니다.

그리고 README.md에 명시되었듯이 현재 학교 홈페이지에 누락된 서비스를 추가하기 위한 웹 페이지를 만들 것입니다. 예를 들어 학교의 각 시설의 기자재 재고 유무 등을 확인할 수 있는 기능을 추가하고 그 외에 학생과 선생님이 온라인으로 학교 운영을 위한 정책을 논의하는데 사용될 토론 및 게시판 기능을 개발할 것으로 결정하였습니다.

이번에는 좀 더 구체적으로 각 웹 페이지의 스토리보드를 그리면서 여기에 어떤 도구(프레임워크, 언어 등)을 이용하여 구현할지, 그리고 틀을 어떻게 잡아야 할지 논의해야 합니다.

또, FWD 프로젝트 저장소를 어느 곳으로 잡아야 할지도 정해야 합니다. 현재 FWD 저장소의 중심이 어디인지 알 수 없기 때문에 Primist 조직 명의의 저장소로 잡아야 할지, 아니면 또 다른 대안이 있을지 찾아보아야 합니다.

**Comment by Las-Wonho** [comment]
새로운 프로젝트에 어떠한 기능이 있어야 하는지 나열해주세요.
