### ISSUE TITLE
이미지 표시 에러

### ISSUE THREAD

**Issue by Las-Wonho** [Las-Wonho/FirstWebDevelop#21]
서버를 실행하였을 경우 이미지가 로딩이 되지 않습니다.

**Comment by Unperknown** [comment]
Flask에서 이미지를 표시할 때에는 url_for 메서드를 jinja2 템플릿으로 씌어야 합니다. 일례로 만약 static 파일에 이미지 파일이 담겨 있으면 HTML 파일에서
<image src="IMAGE LOCATION">에서
<image src="{{ url_for('static', filename='IMAGE LOCATION') }}"로 바꾸어주어야 합니다.
