### ISSUE TITLE
템플릿 폴더 변경 불가 오류

### ISSUE THREAD

**Issue by Las-Wonho** [Las-Wonho/FirstWebDevelop#22]

**Comment by Las-Wonho** [comment]
[이 문서](https://stackoverflow.com/questions/13598363/how-to-dynamically-select-template-directory-to-be-used-in-flask)에 해답이 나와있습니다.

**Comment by Unperknown** [comment]
이 이슈와 관련하여 Pull Request했습니다. 그 곳에서 좀 더 Front-end 팀원과 함께 협의해보아야 합니다.
