### ISSUE TITLE
프로젝트 인원 정하기

### ISSUE THREAD

**Issue by Las-Wonho** [Las-Wonho/FirstWebDevelop#6]
현재 이 프로젝트의 콜라보레이터는 2명입니다.
한명이 아직 들어오지않았는데 들어오시는 것을 추천드립니다.

**Comment by Unperknown** [comment]
굳이 초대 받지 않아도 들어올 수 있는 건가요? 제 생각에는 이 저장소의 장이 직접 초대해야 들어올 수 있을 것 같아서...

**Comment by Las-Wonho** [comment]
직접 초대해야합니다. 그러나 포크한 다음 풀리퀘스트를 하는 것은 누구나 가능합니다. 팀에 들어온다는 것은 모든 권한을 가진다는 의미입니다.
